Algoritmo "atv3_exercicio2"
// Disciplina   : [UC 3: Desenvolver algorítmos]
// Professor   : Mateus Pereira 
// Descrição   : Escreve uma mensagem de boas vindas para um usuário
// Autor(a)    : Gabriel Henrique da Silva Gonçalves
// Data atual  : 27/03/2025
Var
// Seção de Declarações das variáveis 

nome : caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("Qual é o seu nome? ")
leia(nome)

escreva("Seja bem vindo ", nome, "!")

Fimalgoritmo