Algoritmo "guanabara_40"
// Disciplina   : [UC 3: Desenvolver algorítmos]
// Professor   : Mateus Pereira 
// Descrição   : Contagem enquanto 3
// Autor(a)    : Gabriel Henrique da Silva Gonçalves
// Data atual  : 25/04/2025
Var
// Seção de Declarações das variáveis 

contagem : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

enquanto contagem <= 18 faca
         escreva(contagem)
         contagem <- contagem + 3
fimenquanto

escreva(" Acabou!")

Fimalgoritmo