Algoritmo "guanabara_64"
// Disciplina   : UC 3: Desenvolver algorítmos
// Professor   : Mateus de Paula Pereira 
// Descrição   : Mostrando uma contagem com para
// Autor(a)    : Gabriel Henrique da Silva Gonçalves
// Data atual  : 26/05/2025
Var
// Seção de Declarações das variáveis 

i, num : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

para i de 1 ate 9 faca
     escreva(num)
     num <- num + 5
fimpara

escreva(" Acabou!")

Fimalgoritmo