Algoritmo "guanabara_1"
// Disciplina   : [UC 3: Desenvolver algorítmos]
// Professor   : Mateus Pereira 
// Descrição   : Escreva um programa que mostre na tela a mensagem "Olá, Mundo!"
// Autor(a)    : Gabriel Henrique da Silva Gonçalves
// Data atual  : 17/04/2025
Var
// Seção de Declarações das variáveis 

mensagem : caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("Olá Mundo!")

Fimalgoritmo