Algoritmo "atv2_exercicio4"
// Disciplina   : [UC3 - Desenvolver Algoritmos]
// Professor   : Mateus Pereira 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/03/2025
Var
// Seção de Declarações das variáveis 
numero : inteiro
dobro : inteiro
metade : real
c : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
c <- 2
escreva("Digite um número inteiro: ")
leia(numero)
dobro <- numero * c
metade <- numero / c
escreval("O dobro é:", dobro)
escreva("A metade é:", metade)

Fimalgoritmo
//Exercício 04:
//Passo 1: criar a variável ‘numero’ do tipo inteiro
//Passo 2: criar a variável ‘dobro’ do tipo inteiro
//Passo 3: criar a variável ‘metade’ do tipo real
//Passo 4: criar a constante ‘c’ do tipo inteiro
//Passo 5: salvar o valor 2 na constante ‘c’
//Passo 6: informar um número inteiro e salvar na variável ‘numero’
//Passo 7: multiplicar a variável ‘numero’ pela constante ‘c’ e salvar na variável ‘dobro’
//Passo 8: dividir a variável ‘numero’ pela constante ‘c’ e salvar na variável ‘metade’
//Passo 9: mostrar o valor da variável ‘dobro’
//Passo 10: mostrar o valor da variável ‘metade’
