Algoritmo "atv9_exercicio1"
// Disciplina   : [UC 3: Desenvolver algorítmos]
// Professor   : Mateus Pereira 
// Descrição   : Números de 1 a 100
// Autor(a)    : Gabriel Henrique da Silva Gonçalves
// Data atual  : 15/04/2025
Var
// Seção de Declarações das variáveis 

x : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

enquanto x < 100 faca
         x <- x + 1
         escreval(x)
fimenquanto

Fimalgoritmo