Algoritmo "guanabara_2"
// Disciplina   : [UC 3: Desenvolver algorítmos]
// Professor   : Mateus Pereira 
// Descrição   : Mensagem de boas vindas ao usuário
// Autor(a)    : Gabriel Henrique da Silva Gonçalves
// Data atual  : 17/04/2025
Var
// Seção de Declarações das variáveis 

nome : caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("Qual é o seu nome? ")
leia(nome)

escreva("Olá ", nome, " é um prazer te conhecer!")

Fimalgoritmo