Algoritmo "guanabara_65"
// Disciplina   : UC 3: Desenvolver algorítmos
// Professor   : Mateus de Paula Pereira 
// Descrição   : Contagem decrescente com para
// Autor(a)    : Gabriel Henrique da Silva Gonçalves
// Data atual  : 26/05/2025
Var
// Seção de Declarações das variáveis 

i, num : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

num <- 100

para i de 0 ate 10 faca
     escreva(num)
     num <- num - 10
fimpara

escreva(" Acabou!")

Fimalgoritmo