Algoritmo "guanabara_20"
// UC 3: Desenvolver algoritmos
// Mateus 
// Descrição   : Par ou ímpar
// Autor(a)    : Gabriel Henrique da Silva Gonçalves
// Data atual  : 4/18/2025
Var
// Seção de Declarações das variáveis 

numero : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 

escreva("Informe um número:")
leia(numero)

se numero mod 2 = 0 entao
   escreva("O número", numero, " é par")
senao
     escreva("O número", numero, " é ímpar")
fimse

Fimalgoritmo